/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ton_sdk_client_jni_Binding */

#ifndef _Included_ton_sdk_client_jni_Binding
#define _Included_ton_sdk_client_jni_Binding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ton_sdk_client_jni_Binding
 * Method:    tcCreateContext
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ton_sdk_client_jni_Binding_tcCreateContext
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ton_sdk_client_jni_Binding
 * Method:    tcDestroyContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ton_sdk_client_jni_Binding_tcDestroyContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ton_sdk_client_jni_Binding
 * Method:    tcRequest
 * Signature: (JLjava/lang/String;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_ton_sdk_client_jni_Binding_tcRequest
  (JNIEnv *, jclass, jlong, jstring, jstring, jlong);

/*
 * Class:     ton_sdk_client_jni_Binding
 * Method:    tcRequestSync
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ton_sdk_client_jni_Binding_tcRequestSync
  (JNIEnv *, jclass, jlong, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
