/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tonsdkjni_Bridge */

#ifndef _Included_tonsdkjni_Bridge
#define _Included_tonsdkjni_Bridge
#ifdef __cplusplus
extern "C" {
#endif

jint JNI_OnLoad(JavaVM *vm, void *reserved);

/*
 * Class:     tonsdkjni_Bridge
 * Method:    tcCreateContext
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jstring JNICALL Java_tonsdkjni_Bridge_tcCreateContext
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tonsdkjni_Bridge
 * Method:    tcDestroyContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_tonsdkjni_Bridge_tcDestroyContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     tonsdkjni_Bridge
 * Method:    tcRequest
 * Signature: (JLjava/lang/String;Ljava/lang/String;JLscala/Function4;)V
 */
JNIEXPORT void JNICALL Java_tonsdkjni_Bridge_tcRequest
  (JNIEnv *, jobject, jlong, jstring, jstring, jlong);

/*
 * Class:     tonsdkjni_Bridge
 * Method:    tcRequestSync
 * Signature: (JLjava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jstring JNICALL Java_tonsdkjni_Bridge_tcRequestSync
  (JNIEnv *, jobject, jlong, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
