/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TonSdkJniBridge */

#ifndef _Included_TonSdkJniBridge
#define _Included_TonSdkJniBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TonSdkJniBridge
 * Method:    tcCreateContext
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_TonSdkJniBridge_tcCreateContext
  (JNIEnv *, jobject, jstring);

/*
 * Class:     TonSdkJniBridge
 * Method:    tcDestroyContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_TonSdkJniBridge_tcDestroyContext
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
